name: Checkout
on: [push]
jobs:
    Checkout-and-Display-Files:
        runs-on: ubuntu-latest
        steps:
            - name: list files before checkout
              run: ls -a
            - name: Checkout
              run: |
                git init
                git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
                git fetch origin
                git checkout main
            - name: List files after checkout
              run: ls -la