name: Repository Events 2
#on: [push, pull_request, issues]
on:
  push:
  pull_request:
    types: [opened, assigned, reopened, synchronize]
  issues:
    types: [opened]

jobs:
  Checkout-Events:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo $GITHUB_SHA
          echo $GITHUB_REF
      - uses: actions/checkout@v3