name: first-workflow
on: [push]

jobs:
    run-shell-commands:
        runs-on: ubuntu-latest
        steps:
            - name: Print a string
              run: echo "Hello World from Github Actions"
            - name: Multiline Commands
              run: |
                node -v
                npm -v
    parallel-job-macos:
        runs-on: macos-latest
        steps:
            - name: View Software Version
              run: sw_vers
    Dependent-Jobs:
        runs-on: windows-latest
        needs: run-shell-commands
        steps:
            - name: Print a String
              run: Write-Output "Hello from Windows"
            - name: Error Step
              run: Doesnot exists