name: Workflow Trigger
on:
  workflow_dispatch:
    inputs:
      string:
        description: 'Here goes a description'
        type: string
        required: true
        default: "RDx"

      number:
        description: Number is needed
        type: number
        default: 33

      option:
        description: Optionss section
        type: choice
        required: true
        default: "Option 2"
        options:
          - Option 1
          - Option 2
          - Option 3

      boolean:
        description: Input a boolean
        required: false
        type: boolean

      environment:
        description: Environment Section
        type: environment
        required: true

jobs:
  log-info:
    runs-on: ubuntu-latest
    steps:
      - run: echo $GITHUB_REF
      - run: |
          echo "String: ${{ inputs.string }}"
          echo "Number: ${{ inputs.number }}"
          echo "Options: ${{ inputs.option }}"
          echo "Boolean: ${{ inputs.boolean }}"
          echo "Environment: ${{ inputs.environment }}"