name: Working Directory and Shells
on: [push]
defaults:
    run:
        shell: bash
jobs:
    display-working-directory-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - name: Display working directoy and list files
              run: |
                pwd
                ls -a
                echo $GITHUB_SHA
                echo $GITHUB_REPOSITORY
                echo $GITHUB_WORKSPACE

    display-working-directory-windows:
        runs-on: windows-latest
        defaults:
            run:
                shell: pwsh
        steps:
            - name: Display working directoy and list files
              run: |
                Get-Location
                dir
                echo $env:GITHUB_SHA
                echo $env:GITHUB_REPOSITORY
                echo $env:GITHUB_WORKSPACE
            - name: Python Shell
              shell: python
              run: |
                import platform
                print(platform.processor())