name: Workflow Run
on:
  workflow_run:
    workflows: [Repository Events 2]
    types: [completed]

jobs:
  echo-string:
    runs-on: ubuntu-latest
    steps:
      - name: Echo on Completion
        run: echo "Triggered because 'Repository Events 2' was completed"